package dev.naominet.listclient.ui.theme;

import dev.naominet.listclient.utils.font.TTFFontRenderer;
import net.minecraft.client.gui.GuiGraphicsExtractor;

/**
 * Material Design 3 theme for the client's custom UI.
 * <p>
 * A hand-rolled M3 dark color scheme seeded from the client accent
 * {@code #29B6F6}: color roles follow the md.sys token names and MUST be used
 * in their tonal pairs ({@code onX} on {@code X}); depth comes from the
 * surface-container ladder (tonal elevation), not glow shadows; interaction
 * feedback uses state layers (hover 8% / pressed 12% of the on-color).
 * <p>
 * Shapes use the M3 corner scale mapped to GUI pixels (~1.7dp per GUI px):
 * XS≈4dp, S≈8dp, M≈12dp, L≈16dp, plus {@link #pill} for full corners.
 * {@link #roundRect} and {@link #shadow} are pure GL – anti-aliased
 * tessellated geometry via {@link GlShapes}, no textures or images.
 * <p>
 * The type scale is backed by {@link TTFFontRenderer} (MiSans): titles/labels
 * are Medium weight, body is Regular, per the M3 weight-contrast rule.
 */
public final class M3 {

    /* ================================================================== */
    /*  color scheme – dark, Monet dynamic (seed from album art)          */
    /* ================================================================== */

    /** Built-in "Monet Light Blue" seed – used when nothing is playing. */
    public static final int DEFAULT_SEED = 0xFF29B6F6;

    // Non-final: regenerated by applyScheme() when the Monet seed changes.
    // Call sites read M3.PRIMARY etc. at draw time, so they pick up updates
    // automatically. Initialised to the default seed's scheme below.
    public static int PRIMARY, ON_PRIMARY, PRIMARY_CONTAINER, ON_PRIMARY_CONTAINER;
    public static int SECONDARY, ON_SECONDARY, SECONDARY_CONTAINER, ON_SECONDARY_CONTAINER;
    public static int TERTIARY, ON_TERTIARY;
    public static int SURFACE, SURFACE_CONTAINER_LOWEST, SURFACE_CONTAINER_LOW, SURFACE_CONTAINER,
            SURFACE_CONTAINER_HIGH, SURFACE_CONTAINER_HIGHEST, ON_SURFACE, ON_SURFACE_VARIANT;
    public static int OUTLINE, OUTLINE_VARIANT;
    public static int INVERSE_SURFACE, INVERSE_ON_SURFACE;

    // Error stays static – M3 error is a fixed role, not derived from the seed.
    public static final int ERROR = 0xFFFFB4AB;
    public static final int ON_ERROR = 0xFF690005;
    public static final int ERROR_CONTAINER = 0xFF93000A;
    public static final int ON_ERROR_CONTAINER = 0xFFFFDAD6;

    public static final int SCRIM = 0xFF000000;

    static {
        applyScheme(DEFAULT_SEED);
    }

    /** Regenerates every seed-derived color role from a seed. Render-thread only. */
    public static void applyScheme(int seed) {
        int[] s = new int[MonetColor.SCHEME_SIZE];
        MonetColor.darkScheme(seed, s);
        int i = 0;
        PRIMARY = s[i++]; ON_PRIMARY = s[i++]; PRIMARY_CONTAINER = s[i++]; ON_PRIMARY_CONTAINER = s[i++];
        SECONDARY = s[i++]; ON_SECONDARY = s[i++]; SECONDARY_CONTAINER = s[i++]; ON_SECONDARY_CONTAINER = s[i++];
        TERTIARY = s[i++]; ON_TERTIARY = s[i++];
        SURFACE = s[i++]; SURFACE_CONTAINER_LOWEST = s[i++]; SURFACE_CONTAINER_LOW = s[i++];
        SURFACE_CONTAINER = s[i++]; SURFACE_CONTAINER_HIGH = s[i++]; SURFACE_CONTAINER_HIGHEST = s[i++];
        ON_SURFACE = s[i++]; ON_SURFACE_VARIANT = s[i++];
        OUTLINE = s[i++]; OUTLINE_VARIANT = s[i++];
        INVERSE_SURFACE = s[i++]; INVERSE_ON_SURFACE = s[i];
    }

    /* ================================================================== */
    /*  shape scale (GUI px)                                              */
    /* ================================================================== */

    public static final int SHAPE_XS = 2;
    public static final int SHAPE_S = 4;
    public static final int SHAPE_M = 7;
    public static final int SHAPE_L = 9;
    public static final int SHAPE_XL = 14;

    /** Full corners for a component of the given height (buttons, chips). */
    public static int pill(int height) {
        return height / 2;
    }

    /* ================================================================== */
    /*  state layers / alpha                                              */
    /* ================================================================== */

    /** M3 state-layer opacities on an 0-255 alpha scale. */
    public static final int STATE_HOVER = 20;    // 8%
    public static final int STATE_PRESSED = 31;  // 12%
    public static final int DISABLED_CONTENT = 97;   // 38%
    public static final int DISABLED_CONTAINER = 31; // 12%

    /** {@code onColor} at the given alpha – the M3 state layer. */
    public static int stateLayer(int onColor, int alpha) {
        return (onColor & 0x00FFFFFF) | (alpha << 24);
    }

    public static int withAlpha(int argb, int alpha) {
        return (argb & 0x00FFFFFF) | (alpha << 24);
    }

    /** Scales the alpha channel of {@code argb} by {@code f} (0..1). */
    public static int fade(int argb, float f) {
        int a = (int) ((argb >>> 24) * Math.max(0f, Math.min(1f, f)));
        return (argb & 0x00FFFFFF) | (a << 24);
    }

    /** Linear blend between two ARGB colors, all channels. */
    public static int lerp(int a, int b, float t) {
        t = Math.max(0f, Math.min(1f, t));
        int aa = (a >>> 24) + (int) (((b >>> 24) - (a >>> 24)) * t);
        int ar = ((a >> 16) & 255) + (int) ((((b >> 16) & 255) - ((a >> 16) & 255)) * t);
        int ag = ((a >> 8) & 255) + (int) ((((b >> 8) & 255) - ((a >> 8) & 255)) * t);
        int ab = (a & 255) + (int) (((b & 255) - (a & 255)) * t);
        return (aa << 24) | (ar << 16) | (ag << 8) | ab;
    }

    /** Container color with a state layer of its on-color composited on top. */
    public static int layered(int container, int onColor, int layerAlpha) {
        return lerp(container, (onColor & 0x00FFFFFF) | (container & 0xFF000000), layerAlpha / 255f);
    }

    /* ================================================================== */
    /*  type scale (MiSans; Medium for title/label, Regular for body)     */
    /* ================================================================== */

    /*
     * Sized against the HUD module list (label = Medium 8): body text matches
     * it and everything else scales around that, keeping the whole UI compact.
     */

    public static TTFFontRenderer display() {
        return TTFFontRenderer.medium(16);
    }

    public static TTFFontRenderer headline() {
        return TTFFontRenderer.medium(11);
    }

    public static TTFFontRenderer title() {
        return TTFFontRenderer.medium(9);
    }

    public static TTFFontRenderer body() {
        return TTFFontRenderer.get(8);
    }

    public static TTFFontRenderer label() {
        return TTFFontRenderer.medium(8);
    }

    public static TTFFontRenderer labelSmall() {
        return TTFFontRenderer.medium(7);
    }

    /* ================================================================== */
    /*  shapes                                                            */
    /* ================================================================== */

    /**
     * Filled rounded rectangle with anti-aliased corners – pure GL geometry
     * (tessellated quads with vertex-color feathering, see {@link GlShapes}),
     * no textures. Radius is clamped to half the smaller side.
     */
    public static void roundRect(GuiGraphicsExtractor g, int x, int y, int w, int h, int radius, int argb) {
        GlShapes.roundRect(g, x, y, w, h, radius, argb, true, true, true, true);
    }

    /**
     * M3 expressive determinate progress indicator. The inactive track uses the
     * highest surface-container role; the primary indicator travels as a clipped
     * sine band, with {@code phase} supplied from monotonic render time.
     */
    public static float wavePhase() {
        double radians = net.minecraft.util.Util.getMillis() * 0.008;
        return (float) (radians % (Math.PI * 2.0));
    }

    public static void wavyProgress(GuiGraphicsExtractor g, int x, int y, int w, int h,
                                    float progress) {
        if (w <= 0 || h <= 0 || progress <= 0f) return;
        g.enableScissor(x, y, x + w, y + h);
        try {
            GlShapes.wavyBand(g, x, y, w, h, progress, wavePhase(), PRIMARY);
        } finally {
            g.disableScissor();
        }
    }

    /**
     * Album-tinted animated lyric backdrop. The moving translucent fields are
     * submitted through the GPU GUI pipeline; the shader variant can replace
     * this method without changing either lyric surface.
     */
    public static void lyricBackground(GuiGraphicsExtractor g, int x, int y, int w, int h) {
        roundRect(g, x, y, w, h, SHAPE_M, withAlpha(SURFACE_CONTAINER_LOW, 0xF4));
        double time = net.minecraft.util.Util.getMillis() / 1000.0;
        float breathe = 0.96f + (float) Math.sin(time * 0.22) * 0.035f;
        float driftX = (float) (Math.sin(time * 0.115) + Math.sin(time * 0.043 + 1.7))
                * w * 0.026f;
        float driftY = (float) (Math.cos(time * 0.097 + 0.8) + Math.sin(time * 0.037))
                * h * 0.022f;
        float glowW = Math.max(32f, w * 0.72f) * breathe;
        float glowH = Math.max(24f, h * 0.78f) * breathe;
        g.enableScissor(x, y, x + w, y + h);
        try {
            GlShapes.radialGlow(g,
                    x - glowW * 0.28f + driftX,
                    y - glowH * 0.34f + driftY,
                    glowW, glowH, withAlpha(PRIMARY_CONTAINER, 0x58));
            GlShapes.radialGlow(g,
                    x + w - glowW * 0.68f - driftX * 0.72f,
                    y + h - glowH * 0.72f - driftY * 0.8f,
                    glowW * 0.92f, glowH * 0.94f, withAlpha(TERTIARY, 0x34));
            GlShapes.radialGlow(g,
                    x + w * 0.17f - driftX * 0.38f,
                    y + h * 0.25f + driftY * 0.45f,
                    glowW * 0.86f, glowH * 0.84f,
                    withAlpha(SECONDARY_CONTAINER, 0x40));
            GlShapes.radialGlow(g,
                    x + w * 0.32f + driftX * 0.25f,
                    y + h * 0.10f - driftY * 0.2f,
                    glowW * 0.55f, glowH * 0.52f,
                    withAlpha(SURFACE_CONTAINER_HIGHEST, 0x28));
        } finally {
            g.disableScissor();
        }
    }

    /**
     * Rounded rectangle with per-corner control – for surfaces that meet a
     * square edge (e.g. a header rounded only on top). Corners with
     * {@code false} stay square.
     */
    public static void roundRect(GuiGraphicsExtractor g, int x, int y, int w, int h, int radius, int argb,
                                 boolean tl, boolean tr, boolean bl, boolean br) {
        GlShapes.roundRect(g, x, y, w, h, radius, argb, tl, tr, bl, br);
    }

    /**
     * M3 elevation shadow for a floating rounded surface (busy-background
     * exception – tonal elevation stays the default depth cue). Pure GL: the
     * shape outline extruded outward with a quadratic alpha falloff. Draw it
     * immediately before the surface it belongs to.
     */
    public static void shadow(GuiGraphicsExtractor g, int x, int y, int w, int h, int radius) {
        GlShapes.shadow(g, x, y, w, h, radius, 9f, 2f, withAlpha(SCRIM, 0x5A));
    }

    /**
     * M3 keyboard-focus indicator: a crisp primary ring offset just outside
     * the component – never a filled wash. Pure GL like everything else.
     */
    public static void focusRing(GuiGraphicsExtractor g, int x, int y, int w, int h, int radius) {
        GlShapes.ring(g, x, y, w, h, radius, 1.5f, 1.5f, PRIMARY);
    }

    /** Subtle shadow for small HUD elements (module list rows, chips). */
    public static void shadowSoft(GuiGraphicsExtractor g, int x, int y, int w, int h, int radius) {
        GlShapes.shadow(g, x, y, w, h, radius, 4f, 1f, withAlpha(SCRIM, 0x3C));
    }

    /**
     * Frosted-glass backdrop: blurs everything already rendered (world or
     * panorama plus any scrim) before the panel draws on top. Honors the
     * vanilla "Menu Background Blurriness" option like vanilla screens do.
     * Call once per screen, after the scrim, before panel content.
     */
    public static void blurBehind(GuiGraphicsExtractor g) {
        if (net.minecraft.client.Minecraft.getInstance().options.getMenuBackgroundBlurriness() >= 1f) {
            g.nextStratum();
            g.blurBeforeThisStratum();
        }
    }

    /** Outlined variant: 1px {@code outlineArgb} ring around a filled body. */
    public static void outlinedRoundRect(GuiGraphicsExtractor g, int x, int y, int w, int h,
                                         int radius, int fillArgb, int outlineArgb) {
        roundRect(g, x, y, w, h, radius, outlineArgb);
        roundRect(g, x + 1, y + 1, w - 2, h - 2, Math.max(0, radius - 1), fillArgb);
    }

    /** 1px divider – use OUTLINE_VARIANT, never OUTLINE, per M3. */
    public static void divider(GuiGraphicsExtractor g, int x, int y, int w) {
        g.fill(x, y, x + w, y + 1, OUTLINE_VARIANT);
    }

    private M3() {
    }
}
